# =============================================================================
# Konfigurationsdatei: application.properties
# Projekt:             Employee Management System (Backend)
# Beschreibung:        Zentrale Konfiguration fuer die Spring Boot Anwendung.
#                      werden alle allgemeinen und datenbankbezogenen
#                      Einstellungen der Anwendung festgelegt.
# =============================================================================


# Anwendungsname
spring.application.name=employee-management-backend


# Datenbankkonfiguration (MySQL)

# JDBC-Verbindungs-URL zur MySQL-Datenbank
spring.datasource.url=jdbc:mysql://localhost:3306/ems

# Datenbankbenutzer
spring.datasource.username=root

# Datenbankpasswort
spring.datasource.password=${DB_MYSQL_PASSWORD}

# Hibernate erkennt den MySQL-Dialekt automatisch
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate aktualisiert das Datenbankschema automatisch beim Start, ohne Daten zu loeschen
spring.jpa.hibernate.ddl-auto=update